# pytest-django-xdist-cov-bug
Reproducing https://github.com/pytest-dev/pytest-cov/issues/285
